version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=myprojectpassword

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - .:/code
    ports:
      - 8008:8008
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=myproject
      - DATABASE_USER=myprojectuser
      - DATABASE_PASSWORD=myprojectpassword
